# Generated by Django 5.2.3 on 2025-11-17 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration date/time')),
                ('max_uses', models.IntegerField(default=1, help_text='Maximum number of times this token can be used')),
                ('current_uses', models.IntegerField(default=0, help_text='Current number of times this token has been used')),
                ('is_revoked', models.BooleanField(default=False)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='clients.client')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='reports.legalreport')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
                'db_table': 'access_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TokenAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('download_completed', models.BooleanField(default=False)),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='tokens.accesstoken')),
            ],
            options={
                'verbose_name': 'Token Access',
                'verbose_name_plural': 'Token Accesses',
                'db_table': 'token_accesses',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
