# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, help_text='Identificador único del caso (ej: CASE-2024-001)', max_length=50, unique=True, verbose_name='Número de caso')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('case_type', models.CharField(choices=[('civil', 'Civil'), ('penal', 'Penal'), ('laboral', 'Laboral'), ('familiar', 'Familiar'), ('mercantil', 'Mercantil'), ('administrativo', 'Administrativo'), ('otro', 'Otro')], default='civil', max_length=20, verbose_name='Tipo de caso')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En Proceso'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='open', max_length=20, verbose_name='Estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=20, verbose_name='Prioridad')),
                ('opened_at', models.DateField(default=django.utils.timezone.now, help_text='Fecha en que se abrió el caso', verbose_name='Fecha de apertura')),
                ('closed_at', models.DateField(blank=True, help_text='Fecha en que se cerró el caso', null=True, verbose_name='Fecha de cierre')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas visibles solo para el staff', verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Caso',
                'verbose_name_plural': 'Casos',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
