# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['boss', 'employe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['boss', 'employe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['boss', 'employe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cases', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['client', 'status'], name='cases_client__a641c7_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['assigned_to', 'status'], name='cases_assigne_e5cc07_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'priority'], name='cases_status_c72509_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['opened_at'], name='cases_opened__770ade_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['created_at'], name='cases_created_6583ad_idx'),
        ),
    ]
