# Generated by Django 4.2.27 on 2025-12-16 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('subject', models.CharField(max_length=200, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('request_type', models.CharField(choices=[('consultation', 'Consulta'), ('appointment', 'Solicitud de Cita'), ('information', 'Información'), ('other', 'Otro')], default='consultation', max_length=20, verbose_name='Tipo de solicitud')),
                ('status', models.CharField(choices=[('new', 'Nueva'), ('in_progress', 'En Proceso'), ('contacted', 'Contactado'), ('converted', 'Convertido a Cliente'), ('closed', 'Cerrada')], default='new', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas visibles solo para el staff', verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de solicitud')),
            ],
            options={
                'verbose_name': 'Solicitud de Contacto',
                'verbose_name_plural': 'Solicitudes de Contacto',
                'db_table': 'landing_contact_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Puede ser nombre parcial para privacidad (ej: Juan P.)', max_length=100, verbose_name='Nombre del cliente')),
                ('text', models.TextField(help_text='Contenido del testimonio', verbose_name='Testimonio')),
                ('rating', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se muestra en la landing page', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'db_table': 'landing_testimonials',
                'ordering': ['order', '-date'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='landing_tes_is_acti_4c3efd_idx'), models.Index(fields=['rating'], name='landing_tes_rating_b40a4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SuccessCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del caso (sin datos sensibles)', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descripción breve del caso', verbose_name='Descripción')),
                ('case_type', models.CharField(help_text='Tipo de materia (Civil, Penal, Familiar, etc.)', max_length=100, verbose_name='Tipo de caso')),
                ('result', models.TextField(help_text='Resultado obtenido', verbose_name='Resultado')),
                ('date', models.DateField(help_text='Fecha de resolución', verbose_name='Fecha')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se muestra en la landing page', verbose_name='Activo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización', verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Caso de Éxito',
                'verbose_name_plural': 'Casos de Éxito',
                'db_table': 'landing_success_cases',
                'ordering': ['order', '-date'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='landing_suc_is_acti_b36938_idx'), models.Index(fields=['case_type'], name='landing_suc_case_ty_1d877f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, help_text='Clase de FontAwesome (ej: fa-gavel) o ruta de imagen', max_length=100, verbose_name='Icono')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (menor número = primero)', verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo, se muestra en la landing page', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'landing_services',
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['is_active', 'order'], name='landing_ser_is_acti_3930b0_idx')],
            },
        ),
    ]
