# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['boss', 'employe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['status', 'created_at'], name='landing_con_status_99f199_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['request_type'], name='landing_con_request_8c2be7_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['email'], name='landing_con_email_4f6db8_idx'),
        ),
    ]
