# Generated by Django 4.2.27 on 2026-07-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(default='El acceso a este sitio ha sido suspendido. Si sos el titular, regularizá tu situación de pago para reactivarlo de inmediato. Una vez confirmado el pago, el sitio estará disponible nuevamente en minutos.', help_text='Texto que verán los visitantes cuando el sitio esté inhabilitado.', verbose_name='Mensaje para los visitantes'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='maintenance_title',
            field=models.CharField(default='Tu sitio web está temporalmente suspendido', max_length=200, verbose_name='Título de la página de mantenimiento'),
        ),
    ]
