# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by_email', models.EmailField(blank=True, help_text='Email para solicitudes públicas (sin cliente asociado)', max_length=254, verbose_name='Email de solicitante')),
                ('requested_by_name', models.CharField(blank=True, help_text='Nombre para solicitudes públicas', max_length=200, verbose_name='Nombre de solicitante')),
                ('requested_by_phone', models.CharField(blank=True, help_text='Teléfono para solicitudes públicas', max_length=20, verbose_name='Teléfono de solicitante')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='Inicia')),
                ('ends_at', models.DateTimeField(db_index=True, verbose_name='Finaliza')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('appointment_type', models.CharField(choices=[('in_person', 'Presencial'), ('phone', 'Teléfono'), ('video', 'Videollamada')], default='in_person', max_length=20, verbose_name='Tipo de cita')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='confirmed', max_length=20, verbose_name='Estado')),
                ('internal_notes', models.TextField(blank=True, help_text='Notas visibles solo para el staff', verbose_name='Notas internas')),
                ('location', models.CharField(blank=True, help_text='Dirección física para citas presenciales', max_length=250, verbose_name='Ubicación')),
                ('google_calendar_id', models.CharField(blank=True, db_index=True, help_text='ID del evento en Google Calendar', max_length=255, verbose_name='ID de Google Calendar')),
                ('google_meet_link', models.URLField(blank=True, help_text='URL de Google Meet para videollamadas', max_length=500, verbose_name='Enlace de Google Meet')),
                ('last_sync_at', models.DateTimeField(blank=True, help_text='Última vez que se sincronizó con Google Calendar', null=True, verbose_name='Última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'appointments',
                'ordering': ['starts_at'],
            },
        ),
    ]
