# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='case',
            field=models.ForeignKey(blank=True, help_text='Caso relacionado (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='cases.case', verbose_name='Caso'),
        ),
    ]
