# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente asociado (opcional para solicitudes públicas)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client', verbose_name='Cliente'),
        ),
    ]
