# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff que creó la cita (null para solicitudes públicas)', limit_choices_to={'role__in': ['boss', 'employe']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['starts_at', 'status'], name='appointment_starts__4d75a3_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['client', 'starts_at'], name='appointment_client__374de9_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['case', 'starts_at'], name='appointment_case_id_7ceb9e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'starts_at'], name='appointment_status_121451_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['google_calendar_id'], name='appointment_google__af353d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['created_at'], name='appointment_created_e3a5d5_idx'),
        ),
    ]
