# Generated by Django 4.2.27 on 2026-01-05 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='teams_meeting_link',
            field=models.URLField(blank=True, help_text='URL de Microsoft Teams para citas tipo teams', max_length=500, verbose_name='Enlace de Microsoft Teams'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('in_person', 'Presencial'), ('phone', 'Teléfono'), ('video', 'Videollamada'), ('teams', 'Microsoft Teams')], default='in_person', max_length=20, verbose_name='Tipo de cita'),
        ),
        migrations.CreateModel(
            name='LawyerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], db_index=True, help_text='0=Lunes, 6=Domingo', verbose_name='Día de la semana')),
                ('start_time', models.TimeField(help_text='Hora de inicio de disponibilidad', verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(help_text='Hora de fin de disponibilidad', verbose_name='Hora de fin')),
                ('is_active', models.BooleanField(default=True, help_text='Si está activo o deshabilitado temporalmente', verbose_name='Activo')),
                ('slot_duration_minutes', models.IntegerField(default=60, help_text='Duración de cada slot de cita (30, 60, 90 minutos)', verbose_name='Duración de slots (minutos)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('lawyer', models.ForeignKey(help_text='Abogado que configura su disponibilidad', limit_choices_to={'role__in': ['boss', 'employe']}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL, verbose_name='Abogado')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Abogado',
                'verbose_name_plural': 'Disponibilidades de Abogados',
                'db_table': 'lawyer_availability',
                'ordering': ['lawyer', 'day_of_week', 'start_time'],
                'indexes': [models.Index(fields=['lawyer', 'day_of_week', 'is_active'], name='lawyer_avai_lawyer__617576_idx'), models.Index(fields=['is_active'], name='lawyer_avai_is_acti_623faa_idx')],
                'unique_together': {('lawyer', 'day_of_week', 'start_time')},
            },
        ),
    ]
