# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('identification_type', models.CharField(choices=[('ine', 'INE/IFE'), ('passport', 'Pasaporte'), ('rfc', 'RFC'), ('curp', 'CURP'), ('other', 'Otro')], default='ine', max_length=20, verbose_name='Tipo de identificación')),
                ('identification_number', models.CharField(blank=True, max_length=50, verbose_name='Número de identificación')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Dirección')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Código postal')),
                ('notes', models.TextField(blank=True, help_text='Notas visibles solo para el staff', verbose_name='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
