# Generated by Django 4.2.27 on 2025-12-16 11:37

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_path, verbose_name='Archivo')),
                ('original_filename', models.CharField(editable=False, max_length=255, verbose_name='Nombre original')),
                ('file_size', models.PositiveIntegerField(editable=False, help_text='Tamaño del archivo en bytes', verbose_name='Tamaño')),
                ('mime_type', models.CharField(blank=True, editable=False, max_length=100, verbose_name='Tipo MIME')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('document_type', models.CharField(choices=[('contract', 'Contrato'), ('evidence', 'Prueba'), ('resolution', 'Resolución'), ('report', 'Informe'), ('correspondence', 'Correspondencia'), ('identification', 'Identificación'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de documento')),
                ('is_sensitive', models.BooleanField(default=True, help_text='Si es verdadero, requiere código de acceso para descarga por cliente', verbose_name='Sensible')),
                ('uploaded_by_client', models.BooleanField(default=False, help_text='Verdadero si fue subido por el cliente (no staff)', verbose_name='Subido por cliente')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='Notificación enviada')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('upload', 'Documento Subido'), ('view', 'Documento Visualizado'), ('download', 'Documento Descargado'), ('notification_sent', 'Notificación Enviada'), ('code_validated', 'Código Validado'), ('access_denied', 'Acceso Denegado'), ('token_expired', 'Token Expirado')], max_length=20, verbose_name='Tipo de evento')),
                ('success', models.BooleanField(default=True, help_text='Si el evento fue exitoso', verbose_name='Exitoso')),
                ('details', models.TextField(blank=True, help_text='Contexto adicional o mensajes de error', verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de Acceso a Documento',
                'verbose_name_plural': 'Registros de Acceso a Documentos',
                'db_table': 'document_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_type', models.CharField(choices=[('access', 'Código de Acceso'), ('download', 'Token de Descarga')], max_length=10, verbose_name='Tipo de token')),
                ('access_code', models.CharField(blank=True, db_index=True, help_text='Código de 6 dígitos enviado por email (solo para tipo access)', max_length=6, null=True, verbose_name='Código de acceso')),
                ('download_token', models.CharField(blank=True, db_index=True, help_text='Token URL-safe para descarga (solo para tipo download)', max_length=64, null=True, verbose_name='Token de descarga')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('used', models.BooleanField(default=False, verbose_name='Usado')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Usado en')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Contador de intentos de validación', verbose_name='Intentos')),
            ],
            options={
                'verbose_name': 'Token de Acceso a Documento',
                'verbose_name_plural': 'Tokens de Acceso a Documentos',
                'db_table': 'document_access_tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
