# Generated by Django 4.2.27 on 2025-12-16 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0002_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccesstoken',
            name='client',
            field=models.ForeignKey(help_text='Cliente que recibe el código de acceso', limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_document_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='documentaccesstoken',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='documents.document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='documentaccesstoken',
            name='requested_by',
            field=models.ForeignKey(help_text='Staff member quien envió la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='document_access_tokens_created', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='documents.document', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_access_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='document',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case', verbose_name='Caso'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddIndex(
            model_name='documentaccesstoken',
            index=models.Index(fields=['access_code', 'used'], name='document_ac_access__81ecaf_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesstoken',
            index=models.Index(fields=['download_token', 'used'], name='document_ac_downloa_e36c10_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesstoken',
            index=models.Index(fields=['document', 'client', 'token_type'], name='document_ac_documen_aa73fd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesstoken',
            index=models.Index(fields=['expires_at'], name='document_ac_expires_c2ea6c_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['document', 'event_type', 'timestamp'], name='document_ac_documen_2c25f4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='document_ac_user_id_487ba2_idx'),
        ),
        migrations.AddIndex(
            model_name='documentaccesslog',
            index=models.Index(fields=['timestamp'], name='document_ac_timesta_36fb31_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['case', 'document_type'], name='documents_case_id_b5990d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='documents_uploade_d6a956_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_sensitive'], name='documents_is_sens_908a80_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by_client'], name='documents_uploade_f4c15b_idx'),
        ),
    ]
