# Generated by Django 5.2.3 on 2025-11-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(max_length=500, upload_to='reports/%Y/%m/')),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_hash', models.CharField(help_text='MD5 hash for file integrity', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clients.client')),
            ],
            options={
                'verbose_name': 'Legal Report',
                'verbose_name_plural': 'Legal Reports',
                'db_table': 'legal_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
